// Dummy data for exercises (testing purpose)

// Random exercise names
export const randomExerciseNames = [
    'Validate Subsequence',
    'Sorted Cubed Array',
    'Branch Multiplications',
    'Tournament Winner & Losers',
    'Node Depths',
    'Find Cloest value in BST',
    'Depth First Search',
    'Minmum Waiting Time',
    'Knapsack Problem',
    'Two Number Multiplication',
    'Tandem Bicycle',
    'Remove Duplicates from LinkList',
    'Class Photos',
    'Binary Search',
    'Trinary Search',
    'Find Three Largest Numbers',
    'Selection Sort',
    'Bubble Sort',
    'Generate Document',
    'Gereate Daily Report',
    'Caesar Cipher Encryptor',
    'Run-Length Encoding',
    'First Non-Repeating Characters',
    'Longest Peak',
    'Smallest Difference',
    'Largest Difference',
    'Monotinoic Array',
    'Three Number Multiplication',
    'Task Assignment',
    'Move Element To End',
    'Task Assignment',
    'Longest Peak',
    'First Duplicated Value',
    'Array Of Products',
    'Merge Overlapping Intervals',
    'Validate BST',
    'BST Construction',
    'BST Traversal',
    'Spiral Traverse',
    'Reconstruct BST',
    'Binary Tree Diameter',
    'Find Largest of BST',
    'Find Smallest of BST',
    'Find Successor',
    'Max Subset Sum No Adjacent',
    'Min Number Of Coins',
    'Simple Cycle Check',
    'Breatch First Search',
    'Toplological Sort',
    'Height Balanced Binary Tree',
    'Youngest Common Ancestor',
    'Remove Islands',
    'Cycle In Graph',
    'Min Height BST',
    'Min Heap Construction',
    'Sum Of LinkedList',
    'Remove Kth Node From End',
    'Powerset',
    'Permutations',
    'Staircase Traversal',
    'Matrix Multiplication',
    'Sort Stack',
    'Revesrse Stack',
    'Check Palindrome',
    'Next Greater Element',
    'Reverse Words',
    'Valid IP Address',
    'Subarray Sort',
    'Largest Range',
    'Same BSTs',
    'Max Path Sum in Binary Tree',
    "Dijkstra's Algorithm",
    'Find Loop In Graphs',
    'Reverse LinkedList',
    'Merge Linked List',
    'Shift Linked List',
    'Solve Sudoku',
    'Shifted Binary Search',
    'Quick Select',
    'Quick Sort',
    'Pattern Matcher',
    'A* Algorithm',
    'Longest String Chain',
    'Airport Connections',
    'Zip Linked List',
    'Flatten Binary Tree',
    'Minimum Spanning Tree',
];
